config/routes.rb
Rails.application.routes.draw do
  resources :authors
  resources :posts

  root 'posts#index', :as => :home

 get '/about' => 'about#index', :as => :about
 get '/authors/:id/posts' => 'authors#show', :as => :author_posts

end

app/models/author.rb
class Author < ActiveRecord::Base

has_many :posts

end

app/models/post.rb
class Post < ActiveRecord::Base

belongs_to :author

validates_presence_of :title

validate :number_of_characters_short

def number_of_characters_short
    number_of_characters_short = 10 - self.title.length
    if self.title.length < 10
    errors[:base] << "Your title is #{number_of_characters_short} characters short."
    end
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def posts
     Author.find(params[:id]).posts
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:name, :bio)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :author_select, only: [:new, :edit, :update, :create]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page => params[:page], :per_page => 10).order("created_at DESC").all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def author_select
      @author_options = Author.all.collect{ |author| [author.name, author.id] }
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :summary, :author_id, :published)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/views/about/index.html.erb
    <div class="col-md-3 col-sm-3">
        <img class="img-thumbnail img-responsive photo"<%= image_tag 'image2.jpg' %></img>
    </div>
    <div class="col-md-9 col-sm-9">
        <p>
             Hi my real name is Zack Taylor. I've been learning astrology for last 20 years. Yeah, that's true. Sometimes I used to think this is all bullshit. But still I love doing more research on this. Do you know why? I don't know. May be I don't know how to pass time other ways. I've predicted the future for Bill Clinton, George Bush and Osama Binladen. Everything happened as I said. I've even predicted the future for me and unfortunately it's not going like that way.. he hee.
        </p>

        <p>
            I don't know how to fill this paragraph more, so, Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diam nonummy nibh euismod tincidunt ut laoreet dolore magna aliquam erat volutpat. Ut wisi enim ad minim veniam, quis nostrud exerci tation ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Duis autem vel eum iriure dolor in hendrerit in vulputate velit esse molestie consequat, vel illum dolore eu feugiat nulla facilisis at vero eros et accumsan et iusto odio dignissim qui blandit praesent luptatum zzril delenit augue duis dolore te feugait nulla facilisi. Nam liber tempor cum soluta nobis eleifend option congue nihil imperdiet doming id quod mazim placerat facer possim assum.
        </p>
    </div>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%=  %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.bio %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="list-inline">
  <strong>Name:</strong> <%= @author.name %> <strong>Bio:</strong> <%= @author.bio %>
</h3>

<% @author.posts.each do |post| %>
<div class="post-preview">

  <h2 class="post-title">
    <%= post.title %>
  </h2>
  <h3 class="post-subtitle">
    <%= post.body %>
  </h3>
  <h4>
    <%= post.summary %>
  </h4>
<% end %>

<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title><%= yield(:top) %></title>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  </head>
  <body id="<%= params[:controller] %>" class="<%= params[:action] %>">

    <div class="container-fluid">

      <div class="jumbotron">
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <a class="navbar-brand"<%= link_to 'A Morphin Blog', home_path %></a>
            </div>
            <div>
              <ul class="nav navbar-nav">
              </ul>
              <ul id="nav_top" class="nav navbar-nav pull-right">
                <li><a><%= link_to 'About', about_path %></a></li>
                <li><a><%= link_to 'Search', about_path %></a></li>
              </ul>
            </div>
          </div>
        </nav>
      </div>
    </div>

      <div class ="container">
          <div class="row">
        <%= yield %>
          </div>
      </div>
      <div class="container-fluid">
          <hr/>
          <%= yield(:bottom) %>
          <footer class="footer">
            <a class="navbar-brand">Zordon Productions, Copyright 2015. All Rights Reserved.</a>
              <ul class="nav navbar-nav pull-right">
                <li><a href="http://www.toywiz.com/rangerminis.html">Store</a></li>
                <li><a href="http://timelife.com/products/power-rangers-from-mighty-morphin-to-lost-galaxy">DVDS</a></li>
                <li><a href="http://www.letsplaysnes.com/play-mighty-morphin-power-rangers-online/">Video Games</a></li>
                <li><a href="https://www.80stees.com/collections/mighty-morphin-power-rangers">T-Shirts</a></li>
              </ul>
          </div>
        </footer>
  </body>
</html>

app/views/posts/_form.html.erb
<div class="col-xs-10">
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_field :summary %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.select :author_id, options_for_select(@author_options, @post.author_id), :prompt => " "  %>
  </div>
  <div class="field">
    <%= f.label :published %><br>
    <%= f.check_box :published %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<% content_for :top do %>
<%= "Rangers!" %>
<% end %>

<% will_paginate @posts %>

<div class="col-xs-8">
  <% @posts.limit(4).each do |post| %>
  <div class="post-preview">
    <h2 class="post-title">
      <%= post.title %>
    </h2>
    <h3 class="post-subtitle">
      <%= post.summary %>
    </h3>
    <tr>
      <td><%= link_to 'Show', post %></td>
      <td><%= link_to 'Edit', edit_post_path(post) %></td>
      <td><%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <p class="post-meta">Posted by <a><%= post.author.name %></a> on <%= post.created_at.strftime('%B %d, %Y')  %></p>
  </div>
  <hr/>
  <% end %>

  <%= will_paginate @posts %>

</div>

<div class="col-xs-4">
  <div class="aside"><%= image_tag('logo2.jpg') %></img>
    <h5>Zack Taylor</h5>
    <ul class="list-inline">
      <li class="col-xs-4">Twitter</li>
      <li class="col-xs-4">Facebook</li>
      <li class="col-xs-4">Instagram</li>
    </ul>
  </div>
  <div class ="aside_image"><%= image_tag('image2.jpg') %></div>
  <p class="sub-heading">"Looks like it's time to go to work."</p>
  <p class="filler">Quick-witted and clever, Zack relies on a combination of skill, strength, and agility to win his battles. The original Black Ranger. Whenever he didn't have an arm around Trini or Kimberly, Zack could be found pursuing his attractive, but hard-to-get classmate, Angela. Zack always loved a good joke. </p>
</div>

<% content_for :bottom do %>

  <h3 class="headline">MOST POPULAR POSTS</h3>
  <div class="row">
  <% @posts.limit(4).each do |post| %>
      <div id="bottomimage1" class="col-xs-3">
        <%= link_to image_tag(post.author.image), post_path(post.id) %>
        <p class="image_text"><%=  truncate(post.title, :length => 25) %></p>
      </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% content_for :top do %>
<%= @post.title %>
<% end %>

<div class="col-md-3 col-sm-3">
  <img class="img-thumbnail img-responsive photo"><%= image_tag @post.author.image  %></img>

</div>
<div class="col-md-9 col-sm-9">
  <div class="post-preview">
    <h1 class="post-title">
      <%= @post.title %>
    </h1>
    <h3 class="post-body">
      <%= @post.body %>
    </h3>
    <h4 class="post-subtitle">
      <%= @post.summary %>
    </h4>
  </a>
  <p class="post-meta">Posted by <a><%= link_to("#{@post.author.name}", about_path) %></a> one <%= @post.created_at.strftime('%B %d, %Y') %></p>
</div>
</div>
<hr/>